#!/bin/bash

BASE_URL="https://www.voipnovatos.es/voces"

VOICE_VERSION='1.4'

declare -a VOICE_FILES=( \
    'voipnovatos-extra-sounds-es-alaw' \
    'voipnovatos-extra-sounds-es-g729' \
    'voipnovatos-extra-sounds-es-ulaw' \
    'voipnovatos-extra-sounds-es-gsm' \
    'voipnovatos-core-sounds-es-g729' \
    'voipnovatos-core-sounds-es-alaw' \
    'voipnovatos-core-sounds-es-gsm' \
    'voipnovatos-core-sounds-es-ulaw' \
)

do_create_directories() {
    for voice_file in "${VOICE_FILES[@]}"; do
        mkdir -p /usr/src/${voice_file}-${VOICE_VERSION}
        mkdir -p /usr/src/${voice_file}-${VOICE_VERSION}/DEBIAN
        
        touch /usr/src/${voice_file}-${VOICE_VERSION}/DEBIAN/control
        
        wget ${BASE_URL}/${voice_file}-${VOICE_VERSION}.tar.gz -O /usr/src/${voice_file}-${VOICE_VERSION}/${voice_file}-${VOICE_VERSION}.tar.gz --no-check-certificate --no-cache
        cd /usr/src/${voice_file}-${VOICE_VERSION}
        tar -zxf /usr/src/${voice_file}-${VOICE_VERSION}/${voice_file}-${VOICE_VERSION}.tar.gz
        rm /usr/src/${voice_file}-${VOICE_VERSION}/${voice_file}-${VOICE_VERSION}.tar.gz
    done
}

do_create_directories
