#!/bin/bash

ASTERISK_VERSION="11.6-cert11"

DEBIAN_MAINTAINER="Juan Pedro Gonzalez <opensource@jpg-consulting.com>"

do_download_asterisk() {
    wget http://downloads.asterisk.org/pub/telephony/certified-asterisk/certified-asterisk-${ASTERISK_VERSION}.tar.gz -O /usr/src/certified-asterisk-${ASTERISK_VERSION}.tar.gz
    
    cd /usr/src
    tar -zxf /usr/src/certified-asterisk-${ASTERISK_VERSION}.tar.gz
    rm /usr/src/certified-asterisk-${ASTERISK_VERSION}.tar.gz
}

do_make_asterisk()
{
    echo "Installing prerequisites."
    apt-get -y -qq update
    apt-get install -y -qq git-core build-essential libsqlite3-dev libxml2-dev libncurses5-dev libncursesw5-dev libiksemel-dev libssl-dev libeditline-dev libedit-dev curl libcurl4-gnutls-dev
    if [ $? -ne 0 ]; then
        echo "Error: Could not install prerequisites."
        exit 1
    fi
    
    cd /usr/src/certified-asterisk-${ASTERISK_VERSION}
    [ -f /usr/src/certified-asterisk-${ASTERISK_VERSION}/bootstrap.sh ] && /usr/src/certified-asterisk-${ASTERISK_VERSION}/bootstrap.sh
    ./configure
    
    make menuselect
    
}

do_make_chan_dongle() {
    apt-get -y -qq install automake
    
    wget https://github.com/jstasiak/asterisk-chan-dongle/archive/asterisk11.tar.gz -O /usr/src/asterisk-chan-dongle-asterisk11.tar.gz
    
    cd /usr/src
    tar -zxf /usr/src/asterisk-chan-dongle-asterisk11.tar.gz
    rm /usr/src/asterisk-chan-dongle-asterisk11.tar.gz
    
    cd /usr/src/asterisk-chan-dongle-asterisk11
    aclocal && autoconf && automake -a
    
    ./configure --with-asterisk="/usr/src/certified-asterisk-${ASTERISK_VERSION}/include"
    make
}

do_package_config() {
    [ -d /usr/src/certified-asterisk-config-${ASTERISK_VERSION} ] && rm -rf /usr/src/certified-asterisk-config-${ASTERISK_VERSION}
    
    mkdir -p /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/usr/share/doc/asterisk-config/examples/configs/
    mkdir -p /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/etc/asterisk/
    mkdir -p /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/DEBIAN
    
    touch /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/DEBIAN/conffiles
    
    cp /usr/src/certified-asterisk-${ASTERISK_VERSION}/configs/* /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/usr/share/doc/asterisk-config/examples/configs/
    
    for file in /usr/src/certified-asterisk-${ASTERISK_VERSION}/configs/*; do
        dst=${file%.sample}
        dst="/etc/asterisk/${dst##*/}"
        echo "${dst}" >> /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/DEBIAN/conffiles
        cp ${file} /usr/src/certified-asterisk-config-${ASTERISK_VERSION}${dst}
    done

    cat <<EOF > /usr/src/certified-asterisk-config-${ASTERISK_VERSION}/DEBIAN/control
Package: certified-asterisk-config
Source: asterisk
Version: ${ASTERISK_VERSION}
Architecture: all
Maintainer: ${DEBIAN_MAINTAINER}
Recommends: certified-asterisk
Conflicts: asterisk-config-custom, asterisk-config
Section: comm
Priority: optional
Homepage: http://www.asterisk.org/
Description: Configuration files for Asterisk
 Asterisk is an Open Source PBX and telephony toolkit.
 .
 This package contains the default configuration files of Asterisk.    
EOF

    cd /usr/src
    dpkg-deb --build certified-asterisk-config-${ASTERISK_VERSION}/
}

do_download_asterisk
do_package_config
do_make_asterisk
do_make_chan_dongle
