#!/bin/bash

CURRENT_USER_EXTENSION_ID=6000
ASTERISK_DIALPLAN_USERS=6XXX

ASTERISK_USER_EXTENSIONS=()
ASTERISK_TRUNK_PHONENUMBERS=()

ASTERISK_TRUNK_MOVISTAR_FTTH_OUT=''
ASTERISK_TRUNK_MOVISTAR_FTTH_IN=''
COMTREND_VG8050_EXTENSION=''

ASTERISK_PARENTAL_PROTECTION_PIN=''

ASTERISK_SHARED_VOICEMAIL_ENABLED=0
ASTERISK_SHARED_VOICEMAIL_EXTENSION=''
ASTERISK_SHARED_VOICEMAIL_TIMEOUT=20

ASTERISK_MODULE_CHAN_DONGLE_DISA_ENABLED=0
ASTERISK_MODULE_CHAN_DONGLE_DISA_PIN=''
ASTERISK_MODULE_CHAN_DONGLE_DISA_PHONENUMBER=''

RASPBERRY_IP_ADDRESS=''
ASK_TO_REBOOT=0
ASTERISK_MODULE_CHAN_DONGLE_ENABLED=0

do_chan_dongle()
{
    local disa_pin=''
    local disa_pin_confirm=''
    
    gsm_phonenumber=$(whiptail --title "GSM" --inputbox "Introduzca el número de teléfono móvil" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    whiptail --title "GSM" --yesno "¿Desea habilitar DISA en el canal GSM?" 20 60 2 --yes-button Si --no-button No
    if [ $? -eq 0 ]; then
        ASTERISK_MODULE_CHAN_DONGLE_DISA_ENABLED=1
        
        whiptail --title "GSM" --yesno "¿Desea restringir el uso de DISA a un número telefónico?" 20 60 2 --yes-button Si --no-button No
        if [ $? -eq 0 ]; then
            ASTERISK_MODULE_CHAN_DONGLE_DISA_PHONENUMBER=$(whiptail --title "DISA" --inputbox "Introduzca el número de teléfono desde el que accederá a DISA" 20 60 "" 3>&1 1>&2 2>&3)
            if [ $? -ne 0 ]; then
                ASTERISK_MODULE_CHAN_DONGLE_DISA_PHONENUMBER=''
            fi
        fi
        
        while true; do
            disa_pin=$(whiptail --title="DISA" --passwordbox "Introduzca el PIN para acceder a DISA" 20 60 "" 3>&1 1>&2 2>&3)
            if [ $? -ne 0 ]; then
                break
            fi
    
            disa_pin_confirm=$(whiptail --title="DISA" --passwordbox "Vuelva a introducir el PIN para acceder a DISA" 20 60 "" 3>&1 1>&2 2>&3)
            if [ $? -ne 0 ]; then
                break
            fi
        
            if [ "${disa_pin}" = "${disa_pin_confirm}" ]; then
                ASTERISK_MODULE_CHAN_DONGLE_DISA_PIN="${disa_pin}"
                break;
            else
                whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
            fi
        done
    fi

    sed -e "s|^noload => chan_dongle.so|load => chan_dongle.so|" -i /etc/asterisk/modules.conf
    sed -e "s|^exten=+1234567890|exten=+34${gsm_phonenumber}|" -i /etc/asterisk/dongle.conf
    sed -e "s|^context=default|context=from-dongle|" -i /etc/asterisk/dongle.conf
    
    # Guardamos el numero
	ASTERISK_TRUNK_PHONENUMBERS+=( "${gsm_phonenumber}" )
	ASTERISK_MODULE_CHAN_DONGLE_ENABLED=1
}

do_comtrend_vg8050_fxs() {
	# Envía los invites a 192.168.1.3
	dhcp_ip_address=$(ifconfig eth0 | grep -w inet |grep -v 127.0.0.1| awk '{print $2}' | cut -d ":" -f 2)
	dhcp_bcast_address=$(ifconfig eth0 | grep -w inet |grep -v 127.0.0.1| awk '{print $3}' | cut -d ":" -f 2)
	dhcp_netmask=$(ifconfig eth0 | grep -w inet |grep -v 127.0.0.1| awk '{print $4}' | cut -d ":" -f 2)
	dhcp_gateway=$(ip route | awk '/default/ { print $3 }')
	
	IFS=. read -r i1 i2 i3 i4 <<< "${dhcp_ip_address}"
	IFS=. read -r m1 m2 m3 m4 <<< "${dhcp_netmask}"
	dhcp_network=$(printf "%d.%d.%d.%d\n" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))")
	RASPBERRY_IP_ADDRESS=$(echo ${dhcp_network} | awk -F. '$4=3' OFS=".")
	
	whiptail --title "Comtrend VG-8050" --yesno "Para que funcione el puerto FXS del Comtrend VG-8050 necesitamos configurar la dirección IP del Asterisk como ${RASPBERRY_IP_ADDRESS}.\n\n¿Desea continuar?" 20 60 2
    if [ $? -eq 0 ]; then # yes
		cat <<EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

iface eth0 inet static
    address ${RASPBERRY_IP_ADDRESS}
	netmask ${dhcp_netmask}
	network ${dhcp_network}
	broadcast ${dhcp_bcast_address}
	gateway ${dhcp_gateway}
EOF

		cat <<EOF >> /etc/asterisk/sip.conf

[1001]
type=peer
secret=1001
host=dynamic
dtmfmode=inband
qualify=yes
disallow=all
allow=ulaw
allow=alaw
allow=gsm
EOF

		COMTREND_VG8050_EXTENSION=1001
	fi
}

do_dialplan_setup() {
    local ring_all_group=''

    if [ -n "${COMTREND_VG8050_EXTENSION}" ]; then
        ring_all_group="SIP/${COMTREND_VG8050_EXTENSION}"
    fi

    for extension_id in "${ASTERISK_USER_EXTENSIONS[@]}"; do
        if [ -n "${ring_all_group}" ]; then
            ring_all_group="${ring_all_group}&SIP/${extension_id}"
        else
            ring_all_group="SIP/${extension_id}"
        fi
    done

    echo "" >> /etc/asterisk/extensions.conf
    echo "[servicios]" >> /etc/asterisk/extensions.conf
    echo "exten => *97,1,Answer()" >> /etc/asterisk/extensions.conf
    echo "exten => *97,n,VoiceMailMain(\${CALLERID(num)}@default)" >> /etc/asterisk/extensions.conf
    echo "exten => *97,n,Hangup()" >> /etc/asterisk/extensions.conf
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[internas]" >> /etc/asterisk/extensions.conf
    echo "exten => _${ASTERISK_DIALPLAN_USERS},1,Set(TARGETNO=\${EXTEN})" >> /etc/asterisk/extensions.conf
    echo "exten => _${ASTERISK_DIALPLAN_USERS},n,Dial(SIP/\${EXTEN})" >> /etc/asterisk/extensions.conf
    echo "exten => _${ASTERISK_DIALPLAN_USERS},n,Goto(s-\${DIALSTATUS},1)" >> /etc/asterisk/extensions.conf
    if [ -n "${COMTREND_VG8050_EXTENSION}" ]; then
        echo "exten => ${COMTREND_VG8050_EXTENSION},1,Dial(SIP/${COMTREND_VG8050_EXTENSION})"  >> /etc/asterisk/extensions.conf
        echo "exten => ${COMTREND_VG8050_EXTENSION},n,Hangup()"  >> /etc/asterisk/extensions.conf
    fi
    # Si se marca uno de mis números sonarán todos los teléfonos
    for phonenumber in "${ASTERISK_TRUNK_PHONENUMBERS[@]}"; do
        echo "exten => ${phonenumber},1,Dial(${ring_all_group})" >> /etc/asterisk/extensions.conf
        echo "exten => ${phonenumber},n,Hangup()" >> /etc/asterisk/extensions.conf
    done
    # Voicemail
    echo "" >> /etc/asterisk/extensions.conf
    echo "exten => s-NOANSWER,1,Voicemail(\${TARGETNO},u)" >> /etc/asterisk/extensions.con
    echo "exten => s-NOANSWER,n,Hangup()" >> /etc/asterisk/extensions.conf
    echo "" >> /etc/asterisk/extensions.conf
    echo "exten => s-BUSY,1,Voicemail(${TARGETNO},b)" >> /etc/asterisk/extensions.conf
    echo "exten => s-BUSY,n,Hangup()" >> /etc/asterisk/extensions.conf
    echo "" >> /etc/asterisk/extensions.conf
    echo "exten => _s-.,1,Goto(s-NOANSWER,1)" >> /etc/asterisk/extensions.conf
    echo "" >> /etc/asterisk/extensions.conf
    echo "exten => a,1,VoicemailMain(\${EXTEN})" >> /etc/asterisk/extensions.conf
    echo "exten => a,n,Hangup()" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[nacionales]" >> /etc/asterisk/extensions.conf
    echo "exten => _[89]ZXXXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[moviles]" >> /etc/asterisk/extensions.conf
    echo "exten => _6XXXXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf
    echo "exten => _7[1234]XXXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[numeros-inteligente-gratuitos]" >> /etc/asterisk/extensions.conf
    echo "exten => _[89]00XXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[numeros-inteligente-precio-ordinario]" >> /etc/asterisk/extensions.conf
    echo "exten => _90[12]XXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[numeros-inteligente-tarificacion-adicional]" >> /etc/asterisk/extensions.conf
    if [ -n "$ASTERISK_PARENTAL_PROTECTION_PIN" ]; then
        echo "exten => _80[367]XXXXXX,1,Authenticate(${ASTERISK_PARENTAL_PROTECTION_PIN})" >> /etc/asterisk/extensions.conf
        echo "exten => _80[367]XXXXXX,2,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf
        echo "exten => _90[57]XXXXXX,1,Authenticate(${ASTERISK_PARENTAL_PROTECTION_PIN})" >> /etc/asterisk/extensions.conf
        echo "exten => _90[57]XXXXXX,2,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf
    else
        echo "exten => _80[367]XXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf
        echo "exten => _90[57]XXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf
    fi
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[numeros-inteligente-personales]" >> /etc/asterisk/extensions.conf
    echo "exten => _70XXXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[numeros-inteligentes]" >> /etc/asterisk/extensions.conf
    echo "include => numeros-inteligente-gratuitos" >> /etc/asterisk/extensions.conf
    echo "include => numeros-inteligente-precio-ordinario" >> /etc/asterisk/extensions.conf
    echo "include => numeros-inteligente-tarificacion-adicional" >> /etc/asterisk/extensions.conf
    echo "include => numeros-inteligente-personales" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[emergencias]" >> /etc/asterisk/extensions.conf
    echo "exten => 112,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/112)" >> /etc/asterisk/extensions.conf
    echo "exten => 061,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/061)" >> /etc/asterisk/extensions.conf
    echo "exten => 062,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/062)" >> /etc/asterisk/extensions.conf
    echo "exten => 080,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/080)" >> /etc/asterisk/extensions.conf
    echo "exten => 085,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/085)" >> /etc/asterisk/extensions.conf
    echo "exten => 088,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/088)" >> /etc/asterisk/extensions.conf
    echo "exten => 091,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/091)" >> /etc/asterisk/extensions.conf
    echo "exten => 092,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/092)" >> /etc/asterisk/extensions.conf
    echo "exten => 1006,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/1006)" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[informacion-administrativa]" >> /etc/asterisk/extensions.conf
    echo "exten => 010,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/010)" >> /etc/asterisk/extensions.conf
    echo "exten => 012,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/012)" >> /etc/asterisk/extensions.conf
    echo "exten => 060,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/060)" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[atencion-informacion-otros]" >> /etc/asterisk/extensions.conf
    echo "exten => 011,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/011)" >> /etc/asterisk/extensions.conf
    echo "exten => 016,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/016)" >> /etc/asterisk/extensions.conf
    echo "exten => 116XXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[consultas]" >> /etc/asterisk/extensions.conf
    echo "exten => _118XX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[atencion-clientes]" >> /etc/asterisk/extensions.conf
    echo "exten => _1[34567]XX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf
    echo "exten => _[12]2XX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[llamada-oculta]" >> /etc/asterisk/extensions.conf
    echo "exten => 069,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/069)" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo ";[seleccion-operador]" >> /etc/asterisk/extensions.conf
    echo "; Códigos de selección de operador" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[numeros-cortos]" >> /etc/asterisk/extensions.conf
    echo "include => emergencias" >> /etc/asterisk/extensions.conf
    echo "include => informacion-administrativa" >> /etc/asterisk/extensions.conf
    echo "include => atencion-informacion-otros" >> /etc/asterisk/extensions.conf
    echo "include => consultas" >> /etc/asterisk/extensions.conf
    echo "include => atencion-clientes" >> /etc/asterisk/extensions.conf
    echo "include => llamada-oculta" >> /etc/asterisk/extensions.conf
    echo ";include => seleccion-operador" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[nomadas]" >> /etc/asterisk/extensions.conf
    echo "exten => _51XXXXXXXXX,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[internacionales]" >> /etc/asterisk/extensions.conf
    echo "exten => _00XXXXXX.,1,Dial(${ASTERISK_TRUNK_MOVISTAR_FTTH_OUT}/\${EXTEN})" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[salientes]" >> /etc/asterisk/extensions.conf
    echo "include => nacionales" >> /etc/asterisk/extensions.conf
    echo "include => moviles" >> /etc/asterisk/extensions.conf
    echo "include => numeros-inteligentes" >> /etc/asterisk/extensions.conf
    echo "include => numeros-cortos" >> /etc/asterisk/extensions.conf
    echo "include => nomadas" >> /etc/asterisk/extensions.conf
    echo "include => internacionales" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[outbound-movistar]" >> /etc/asterisk/extensions.conf
	echo "include => internas" >> /etc/asterisk/extensions.conf
    echo "include => nacionales" >> /etc/asterisk/extensions.conf
    echo "include => moviles" >> /etc/asterisk/extensions.conf
    echo "include => numeros-inteligentes" >> /etc/asterisk/extensions.conf
    echo "include => numeros-cortos" >> /etc/asterisk/extensions.conf
    echo "include => nomadas" >> /etc/asterisk/extensions.conf
    echo "include => internacionales" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[from-internal]" >> /etc/asterisk/extensions.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[from-external]" >> /etc/asterisk/extensions.conf
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[from-movistar]" >> /etc/asterisk/extensions.conf
	echo "include => internas" >> /etc/asterisk/extensions.conf
	if [ $ASTERISK_SHARED_VOICEMAIL_ENABLED --eq 1 ]; then
		echo "exten => s,1,Dial(${ring_all_group}, ${ASTERISK_SHARED_VOICEMAIL_TIMEOUT})" >> /etc/asterisk/extensions.conf
        echo "exten => s,n,Goto(s-\${DIALSTATUS},1)" >> /etc/asterisk/extensions.conf
        echo "" >> /etc/asterisk/extensions.conf
		echo "exten => s-NOANSWER,1,Voicemail(${ASTERISK_SHARED_VOICEMAIL_EXTENSION},u)" >> /etc/asterisk/extensions.conf
		echo "exten => s-NOANSWER,n,Hangup()" >> /etc/asterisk/extensions.conf
		echo "" >> /etc/asterisk/extensions.conf
		echo "exten => s-BUSY,1,Voicemail(${ASTERISK_SHARED_VOICEMAIL_EXTENSION},b)" >> /etc/asterisk/extensions.conf
		echo "exten => s-BUSY,n,Hangup()" >> /etc/asterisk/extensions.conf
		echo "" >> /etc/asterisk/extensions.conf
		echo "exten => _s-.,1,Goto(s-NOANSWER,1)" >> /etc/asterisk/extensions.conf
		echo "" >> /etc/asterisk/extensions.conf
		echo "exten => a,1,VoicemailMain(${ASTERISK_SHARED_VOICEMAIL_EXTENSION})" >> /etc/asterisk/extensions.conf
		echo "exten => a,n,Hangup()" >> /etc/asterisk/extensions.conf
	else
		echo "exten => s,1,Dial(${ring_all_group})" >> /etc/asterisk/extensions.conf
	fi
	
	# chan_dongle module
	if [ $ASTERISK_MODULE_CHAN_DONGLE_ENABLED -eq 1 ]; then
        echo "" >> /etc/asterisk/extensions.conf
        echo "[from-dongle]" >> /etc/asterisk/extensions.conf
        echo "exten => sms,1,Verbose(Incoming SMS from \${CALLERID(num)} \${BASE64_DECODE(\${SMS_BASE64})})" >> /etc/asterisk/extensions.conf
        echo "exten => sms,n,Hangup()" >> /etc/asterisk/extensions.conf
        
        if [ $ASTERISK_MODULE_CHAN_DONGLE_DISA_ENABLED -eq 1 ]; then
            if [ -n "${ASTERISK_MODULE_CHAN_DONGLE_DISA_PHONENUMBER}" ]; then
                echo "exten => _.,1,GotoIf(\$[\"\${CALLERID(num)}\" = \"${ASTERISK_MODULE_CHAN_DONGLE_DISA_PHONENUMBER}\"]?500)" >> /etc/asterisk/extensions.conf
            else
                echo "exten => _.,1,Answer()" >> /etc/asterisk/extensions.conf
                if [ -n "$ASTERISK_MODULE_CHAN_DONGLE_DISA_PIN" ]; then
                    echo "exten => _.,2,Authenticate(${ASTERISK_MODULE_CHAN_DONGLE_DISA_PIN})" >> /etc/asterisk/extensions.conf
                    echo "exten => _.,3,Background(vm-enter-num-to-call)" >> /etc/asterisk/extensions.conf
                    echo "exten => _.,4,DISA(no-password, public)" >> /etc/asterisk/extensions.conf
                fi
            fi
        fi
        
        echo "exten => _.,10,Set(CALLERID(name)=\${CALLERID(num)})" >> /etc/asterisk/extensions.conf
        echo "exten => _.,11,Dial(${ring_all_group})" >> /etc/asterisk/extensions.conf
        
        if [ $ASTERISK_MODULE_CHAN_DONGLE_DISA_ENABLED -eq 1 ]; then
            if [ -n "${ASTERISK_MODULE_CHAN_DONGLE_DISA_PHONENUMBER}" ]; then
                echo "exten => _.,499,Hangup()" >> /etc/asterisk/extensions.conf
                echo "exten => _.,500,Answer()" >> /etc/asterisk/extensions.conf
                if [ -n "$ASTERISK_MODULE_CHAN_DONGLE_DISA_PIN" ]; then
                    echo "exten => _.,501,Authenticate(${ASTERISK_MODULE_CHAN_DONGLE_DISA_PIN})" >> /etc/asterisk/extensions.conf
                    echo "exten => _.,502,Background(vm-enter-num-to-call)" >> /etc/asterisk/extensions.conf
                    echo "exten => _.,503,DISA(no-password, public)" >> /etc/asterisk/extensions.conf
                else
                    echo "exten => _.,501,Background(vm-enter-num-to-call)" >> /etc/asterisk/extensions.conf
                    echo "exten => _.,502,DISA(no-password, public)" >> /etc/asterisk/extensions.conf
                fi
            fi
        fi
    fi

    sed -e "s|^include => demo|include => outbound-movistar|" -i /etc/asterisk/extensions.conf
}

do_expand_rootfs() {
    if ! [ -h /dev/root ]; then
        whiptail --msgbox "/dev/root does not exist or is not a symlink. Don't know how to expand" 20 60 2
        return 0
    fi

    ROOT_PART=$(readlink /dev/root)
    PART_NUM=${ROOT_PART#mmcblk0p}
    if [ "$PART_NUM" = "$ROOT_PART" ]; then
        whiptail --msgbox "/dev/root is not an SD card. Don't know how to expand" 20 60 2
        return 0
    fi

    # NOTE: the NOOBS partition layout confuses parted. For now, let's only 
    # agree to work with a sufficiently simple partition layout
    if [ "$PART_NUM" -ne 2 ]; then
        whiptail --msgbox "Your partition layout is not currently supported by this tool. You are probably using NOOBS, in which case your root filesystem is already expanded anyway." 20 60 2
        return 0
    fi

    LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)

    if [ "$LAST_PART_NUM" != "$PART_NUM" ]; then
        whiptail --msgbox "/dev/root is not the last partition. Don't know how to expand" 20 60 2
        return 0
    fi

    # Get the starting offset of the root partition
    PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d:)
    [ "$PART_START" ] || return 1
    # Return value will likely be error for fdisk as it fails to reload the
    # partition table because the root fs is mounted
    fdisk /dev/mmcblk0 <<EOF
p
d
$PART_NUM
n
p
$PART_NUM
$PART_START

p
w
EOF
    ASK_TO_REBOOT=1

    # now set up an init.d script
cat <<\EOF > /etc/init.d/resize2fs_once &&
#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
    start)
        log_daemon_msg "Starting resize2fs_once" &&
        resize2fs /dev/root &&
        rm /etc/init.d/resize2fs_once &&
        update-rc.d resize2fs_once remove &&
        log_end_msg $?
        ;;
    *)
        echo "Usage: $0 start" >&2
        exit 3
        ;;
esac
EOF
    chmod +x /etc/init.d/resize2fs_once &&
    update-rc.d resize2fs_once defaults &&
    whiptail --msgbox "El tamaño de la partición raíz ha sido modificado.\nEl sistema de archivos se agrandará en el próximo reinicio." 20 60 2
}

do_finish() {
    # Disable setup at boot
    if [ -e /etc/profile.d/setup-asterisk.sh ]; then
        rm -f /etc/profile.d/setup-asterisk.sh
    fi

	service asterisk restart

    if [ $ASK_TO_REBOOT -eq 1 ]; then
        whiptail --yesno "Debe reiniciar el equipo para poder aplicar la configuración.\n\n¿Desea reiniciar ahora?" 20 60 2
        if [ $? -eq 0 ]; then # yes
			if [ -n "${RASPBERRY_IP_ADDRESS}" ]; then
                whiptail --msgbox "La dirección IP tras el reinicio será ${RASPBERRY_IP_ADDRESS}" 20 60 1
            fi
            sync
            reboot
        fi
    fi
    exit 0
}

do_movistar_sip_account() {
    local movistar_phonenumber=''
    local movistar_domain='telefonica.net'
    local movistar_domain_port='5060'
    local movistar_outboundproxy='10.31.255.134'
    local movistar_outboundproxy_port='5070'
    local movistar_dtmfmode='auto'
	
    movistar_phonenumber=$(whiptail --title="Movistar VoIP" --inputbox "Introduzca su número de teléfono fijo" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi

	cat <<EOF >> /etc/asterisk/sip.conf

[Movistar](!)
type=peer
secret=${movistar_phonenumber}
dtmfmode=${movistar_dtmfmode}
insecure=port,invite
outboundproxy=${movistar_outboundproxy}:${movistar_outboundproxy_port}
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[MovistarOut](Movistar)
host=${movistar_domain}
from-domain=${movistar_domain}
fromuser=${movistar_phonenumber}

[MovistarIn](Movistar)
context=from-movistar
defaultuser=${movistar_phonenumber}
host=${movistar_outboundproxy}
port=${movistar_domain_port}
qualify=no
trustpid=yes
EOF

    # El registro en el servidor SIP de movistar
    sed -e "s|^;register => 2345:password@sip_proxy/1234|;register => 2345:password@sip_proxy/1234\nregister => ${movistar_phonenumber}@${movistar_domain}:${movistar_phonenumber}@${movistar_outboundproxy}:${movistar_outboundproxy_port}|" -i /etc/asterisk/sip.conf

    # Guardamos el numero
    ASTERISK_TRUNK_PHONENUMBERS+=( "${movistar_phonenumber}" )

    # Guardamos los trunks
    ASTERISK_TRUNK_MOVISTAR_FTTH_OUT="SIP/MovistarOut"
    ASTERISK_TRUNK_MOVISTAR_FTTH_IN='SIP/MovistarIn'
}

do_parental_protection_set_pin() {
	local parental_protection_password=''
	local parental_protection_password_confirm=''
	
	while true; do
        parental_protection_password=$(whiptail --title="Control Parental" --passwordbox "Introduzca el PIN de control parental" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            return 1
        fi
    
        parental_protection_password_confirm=$(whiptail --title="Control Parental" --passwordbox "Vuelva a introducir el PIN de control parental" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            return 1
        fi
        
        if [ "${parental_protection_password}" = "${parental_protection_password_confirm}" ]; then
			ASTERISK_PARENTAL_PROTECTION_PIN="${parental_protection_password}"
            break;
        else
            whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
        fi
    done
}

do_shared_voicemail() {
    local voicemail_extension=''
    local voicemail_pin=''
    local voicemail_pin_confirm=''
    local voicemail_email=''
    local whiptail_title="Buzón de voz"
    
    voicemail_extension=$(whiptail --title="${whiptail_title}" --inputbox "Introduzca la extensión para el buzón de voz compartido" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    while true; do
        voicemail_pin=$(whiptail --title="${whiptail_title}" --passwordbox "Introduzca el PIN del buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            voicemail_pin=''
            continue
        fi
    
        voicemail_pin_confirm=$(whiptail --title="${whiptail_title}" --passwordbox "Vuelva a introducir el PIN del buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            voicemail_pin=''
            continue
        fi
        
        if [ "${voicemail_pin}" = "${voicemail_pin_confirm}" ]; then
            break
        else
            whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
        fi
    done

    voicemail_email=$(whiptail --title="${whiptail_title}" --inputbox "Introduzca el correo electrónico del buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        voicemail_email=''
    fi

    # Configuración
    sed -e "s|^\[default\]|\[default\]\n${voicemail_extension} => ${voicemail_pin},Buzón de voz compartido,${voicemail_email}|" -i /etc/asterisk/voicemail.conf

    # Establecer las variables globales
    ASTERISK_SHARED_VOICEMAIL_ENABLED=1
    ASTERISK_SHARED_VOICEMAIL_EXTENSION="${voicemail_extension}"
    ASTERISK_SHARED_VOICEMAIL_TIMEOUT=20
    
    return 0
}

do_user_add() {
	local extension_fullname=''
	local extension_email=''
	local extension_password=''
	local extension_password_confirm=''
	local extension_vmsecret=''
	local extension_vmsecret_confirm=''
	
	local whiptail_title="Nueva extensión: ${CURRENT_USER_EXTENSION_ID}"
	
    while true; do
        extension_password=$(whiptail --title="${whiptail_title}" --passwordbox "Introduzca la contraseña de la extensión" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            return 1
        fi
    
        extension_password_confirm=$(whiptail --title="${whiptail_title}" --passwordbox "Vuelva a introducir la contraseña de la extensión" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            return 1
        fi
        
        if [ "${extension_password}" = "${extension_password_confirm}" ]; then
            break
        else
            whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
        fi
    done
	
	extension_fullname=$(whiptail --title="${whiptail_title}" --inputbox "Introduzca el nombre completo del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        extension_fullname=''
    fi
	
	extension_email=$(whiptail --title="${whiptail_title}" --inputbox "Introduzca el correo electrónico del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        extension_email=''
    fi
	
	if [ $ASTERISK_SHARED_VOICEMAIL_ENABLED -eq 0 ]; then
	    whiptail --title="${whiptail_title}" --yesno "¿Desea activar el buzón de voz para ésta extensión?" 20 60 2 --defaultno
        if [ $? -eq 0 ]; then # yes
		    while true; do
			    extension_vmsecret=$(whiptail --title="${whiptail_title}" --passwordbox "Introduzca el código PIN para el buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
			    if [ $? -ne 0 ]; then
				    whiptail --title="${whiptail_title}" --yesno "¿Desea activar el buzón de voz para ésta extensión?" 20 60 2
				    if [ $? -eq 0 ]; then # yes
					    continue
				    else
					    break
				    fi
			    fi
    
			    extension_vmsecret_confirm=$(whiptail --title="${whiptail_title}" --passwordbox "Vuelva a introducir el código PIN para el buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
			    if [ $? -ne 0 ]; then
				    extension_vmsecret=''
				    whiptail --title="${whiptail_title}" --yesno "¿Desea activar el buzón de voz para ésta extensión?" 20 60 2
				    if [ $? -eq 0 ]; then # yes
					    continue
				    else
					    break
				    fi
			    fi
        
			    if [ "${extension_vmsecret}" = "${extension_vmsecret_confirm}" ]; then
				    break;
			    else
				    whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
			    fi
		    done
        fi
	fi
	
	# Write
	echo "" >> /etc/asterisk/users.conf
	echo "[${CURRENT_USER_EXTENSION_ID}]" >> /etc/asterisk/users.conf
	echo "host=dynamic" >> /etc/asterisk/users.conf
	if [ -n "${extension_fullname}" ]; then
        echo "fullname = ${extension_fullname}" >> /etc/asterisk/users.conf
    fi
	
	if [ -n "${extension_email}" ]; then
        echo "email = ${extension_email}" >> /etc/asterisk/users.conf
    fi
		
	echo "secret = ${extension_password}" >> /etc/asterisk/users.conf
	
	if [ -n "${extension_vmsecret}" ]; then
        echo "hasvoicemail = yes" >> /etc/asterisk/users.conf
		echo "vmsecret = ${extension_vmsecret}" >> /etc/asterisk/users.conf
    fi

    if [ $ASTERISK_SHARED_VOICEMAIL_ENABLED -eq 1 ];then
        [ ! -d /var/spool/asterisk/voicemail/default/${ASTERISK_SHARED_VOICEMAIL_EXTENSION} ] && mkdir -p /var/spool/asterisk/voicemail/default/${ASTERISK_SHARED_VOICEMAIL_EXTENSION}
        ln -s /var/spool/asterisk/voicemail/default/${ASTERISK_SHARED_VOICEMAIL_EXTENSION} /var/spool/asterisk/voicemail/default/${CURRENT_USER_EXTENSION_ID}
    fi
    
	ASTERISK_USER_EXTENSIONS+=( "${CURRENT_USER_EXTENSION_ID}" )
	((CURRENT_USER_EXTENSION_ID=CURRENT_USER_EXTENSION_ID+1))
}


# Wizzard

whiptail --title "Tarjeta SD" --yesno "¿Desea expandir el sistema de archivos?" 20 60 2 --yes-button Si --no-button No
if [ $? -eq 0 ]; then
	do_expand_rootfs
fi

whiptail --title "Buzón de voz" --yesno "¿Desea utilizar un buzón de voz compartido?" 20 60 1 --yes-button Si --no-button No
if [ $? -eq 0 ]; then
    do_shared_voicemail
    ASTERISK_SHARED_VOICEMAIL_ENABLED=1
else
    [ -f /usr/bin/groupwmi ] && rm /usr/bin/groupwmi
fi

whiptail --title "Extensiones" --yesno "¿Desea crear algún usuario?" 20 60 2 --yes-button Si --no-button No
if [ $? -eq 0 ]; then
	while true; do
		do_user_add
		whiptail --title "Extensiones" --yesno "¿Desea agregar otro usuario?" 20 60 2 --defaultno --yes-button Si --no-button No
		if [ $? -eq 1 ]; then
			break
		fi
	done
fi

whiptail --title "Movistar" --yesno "¿Desea configurar una cuenta SIP de Movistar?" 20 60 2 --yes-button Si --no-button No
if [ $? -eq 0 ]; then
	do_movistar_sip_account

	# ToDo: Detectar el router por la IP... si es comtrend lanzar esto
	whiptail --title "Comtrend VG-8050" --yesno "¿Desea configurar el Comtrend VG-8050 para utilizar los teléfonos analógicos?" 20 60 2 --yes-button Si --no-button No
	if [ $? -eq 0 ]; then
		do_comtrend_vg8050_fxs
	fi
fi

if [ -f /usr/lib/asterisk/modules/chan_dongle.so ]; then
    whiptail --title "GSM" --yesno "¿Desea configurar el módulo chan_dongle?" 20 60 2 --defaultno --yes-button Si --no-button No
    if [ $? -eq 0 ]; then
        do_chan_dongle
    fi
fi

whiptail --title "Control Parental" --yesno "¿Desea activar el control parental?" 20 60 2 --yes-button Si --no-button No
if [ $? -eq 0 ]; then
	do_parental_protection_set_pin

	# ToDo: Definir reglas de control parental
fi

do_dialplan_setup

do_finish
