#!/bin/bash

CURRENT_USER_EXTENSION_ID=6000
ASTERISK_USER_EXTENSIONS=()
ASTERISK_TRUNK_PHONENUMBERS=()

ASTERISK_TRUNK_MOVISTAR_FTTH_OUT=''
ASTERISK_TRUNK_MOVISTAR_FTTH_IN=''

do_comtrend_vg8050_fxs() {
	# Envía los invites a 192.168.1.3
	dhcp_ip_address=$(ifconfig eth0 | grep -w inet |grep -v 127.0.0.1| awk '{print $2}' | cut -d ":" -f 2)
	dhcp_bcast_address=$(ifconfig eth0 | grep -w inet |grep -v 127.0.0.1| awk '{print $3}' | cut -d ":" -f 2)
	dhcp_netmask=$(ifconfig eth0 | grep -w inet |grep -v 127.0.0.1| awk '{print $4}' | cut -d ":" -f 2)
	dhcp_gateway=$(ip route | awk '/default/ { print $3 }')
	
	IFS=. read -r i1 i2 i3 i4 <<< "${dhcp_ip_address}"
	IFS=. read -r m1 m2 m3 m4 <<< "${dhcp_netmask}"
	dhcp_network=$(printf "%d.%d.%d.%d\n" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))")
	RASPBERRY_IP_ADDRESS=$(echo ${dhcp_network} | awk -F. '$4=3' OFS=".")
	
	whiptail --title "Comtrend VG-8050" --yesno "Para que funcione el puerto FXS del Comtrend VG-8050 necesitamos configurar la dirección IP del Asterisk como ${RASPBERRY_IP_ADDRESS}.\n\n¿Desea continuar?" 20 60 2
    if [ $? -eq 0 ]; then # yes
		cat <<EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

iface eth0 inet static
    address ${RASPBERRY_IP_ADDRESS}
	netmask ${dhcp_netmask}
	network ${dhcp_network}
	broadcast ${dhcp_bcast_address}
	gateway ${dhcp_gateway}
EOF

		cat <<EOF >> /etc/asterisk/sip.conf

[1001]
type=peer
secret=1001
host=dynamic
dtmfmode=inband
qualify=yes
disallow=all
allow=ulaw
allow=alaw
allow=gsm
EOF
	fi
}

do_movistar_sip_account() {
	local movistar_phonenumber=''
	local movistar_domain='telefonica.net'
	local movistar_domain_port='5060'
	local movistar_outboundproxy='10.31.255.134'
	local movistar_outboundproxy_port='5070'
	local movistar_dtmfmode='auto'
	
	movistar_phonenumber=$(whiptail --title="Movistar VoIP" --inputbox "Introduzca su número de teléfono fijo" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
	
	cat <<EOF >> /etc/asterisk/sip.conf

[Movistar](!)
type=peer
secret=${movistar_phonenumber}
dtmfmode=${movistar_dtmfmode}
insecure=port,invite
outboundproxy=${movistar_outboundproxy}:${movistar_outboundproxy_port}
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[MovistarOut](Movistar)
host=${movistar_domain}
from-domain=${movistar_domain}
fromuser=${movistar_phonenumber}

[MovistarIn](Movistar)
context=from-movistar
defaultuser=${movistar_phonenumber}
host=${movistar_outboundproxy}
port=${movistar_domain_port}
qualify=no
trustpid=yes
EOF
	
	# El registro en el servidor SIP de movistar
	sed -e "s|^;register => 2345:password@sip_proxy/1234|;register => 2345:password@sip_proxy/1234\nregister => ${movistar_phonenumber}@${movistar_domain}:${movistar_phonenumber}@${movistar_outboundproxy}:${movistar_outboundproxy_port}|" -i /etc/asterisk/sip.conf

	# Guardamos el numero
	ASTERISK_TRUNK_PHONENUMBERS+=( "${movistar_phonenumber}" )
	
	# Guardamos los trunks
	ASTERISK_TRUNK_MOVISTAR_FTTH_OUT="SIP/MovistarOut"
	ASTERISK_TRUNK_MOVISTAR_FTTH_IN='SIP/MovistarIn'
}

do_user_add() {
	local extension_fullname=''
	local extension_email=''
	local extension_password=''
	local extension_password_confirm=''
	local extension_vmsecret=''
	local extension_vmsecret_confirm=''
	
	local whiptail_title="Nueva extensión: ${CURRENT_USER_EXTENSION_ID}"
	
    while true; do
        extension_password=$(whiptail --title="${whiptail_title}" --passwordbox "Introduzca la contraseña de la extensión" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            return 1
        fi
    
        extension_password_confirm=$(whiptail --title="${whiptail_title}" --passwordbox "Vuelva a introducir la contraseña de la extensión" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            return 1
        fi
        
        if [ "${extension_password}" = "${extension_password_confirm}" ]; then
            break;
        else
            whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
        fi
    done
	
	extension_fullname=$(whiptail --title="${whiptail_title}" --inputbox "Introduzca el nombre completo del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        extension_fullname=''
    fi
	
	extension_email=$(whiptail --title="${whiptail_title}" --inputbox "Introduzca el correo electrónico del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        extension_email=''
    fi
	
	whiptail --title="${whiptail_title}" --yesno "¿Desea activar el buzón de voz para ésta extensión?" 20 60 2
    if [ $? -eq 0 ]; then # yes
		while true; do
			extension_vmsecret=$(whiptail --title="${whiptail_title}" --passwordbox "Introduzca el código PIN para el buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
			if [ $? -ne 0 ]; then
				whiptail --title="${whiptail_title}" --yesno "¿Desea activar el buzón de voz para ésta extensión?" 20 60 2
				if [ $? -eq 0 ]; then # yes
					continue
				else
					break
				fi
			fi
    
			extension_vmsecret_confirm=$(whiptail --title="${whiptail_title}" --passwordbox "Vuelva a introducir el código PIN para el buzón de voz" 20 60 "" 3>&1 1>&2 2>&3)
			if [ $? -ne 0 ]; then
				extension_vmsecret=''
				whiptail --title="${whiptail_title}" --yesno "¿Desea activar el buzón de voz para ésta extensión?" 20 60 2
				if [ $? -eq 0 ]; then # yes
					continue
				else
					break
				fi
			fi
        
			if [ "${extension_vmsecret}" = "${extension_vmsecret_confirm}" ]; then
				break;
			else
				whiptail --title "Error" --msgbox "Las contraseñas no coinciden." 20 60 2
			fi
		done
	fi
	
	# Write
	echo "" >> /etc/asterisk/users.conf
	if [ -n "${extension_fullname}" ]; then
        echo "fullname = ${extension_fullname}" >> /etc/asterisk/users.conf
    fi
	
	if [ -n "${extension_email}" ]; then
        echo "email = ${extension_email}" >> /etc/asterisk/users.conf
    fi
		
	echo "secret = ${extension_password}" >> /etc/asterisk/users.conf
	
	if [ -n "${extension_vmsecret}" ]; then
        echo "hasvoicemail = yes" >> /etc/asterisk/users.conf
		echo "vmsecret = ${extension_vmsecret}" >> /etc/asterisk/users.conf
    fi
	
	ASTERISK_USER_EXTENSIONS+=( "${CURRENT_USER_EXTENSION_ID}" )
	((CURRENT_USER_EXTENSION_ID=CURRENT_USER_EXTENSION_ID+1))
}


# Wizzard

whiptail --title "Extensiones" --yesno "¿Desea crear algún usuario?" 20 60 2 --defaultyes --yes-button Si --no-button No
if [ $? -eq 0 ]; then
	while true; do
		do_user_add
		whiptail --title "Extensiones" --yesno "¿Desea agregar otro usuario?" 20 60 2 --defaultno --yes-button Si --no-button No
		if [ $? -eq 1 ]; then
			break
		fi
	done
fi

whiptail --title "Movistar" --yesno "¿Desea configurar una cuenta SIP de Movistar?" 20 60 2 --defaultyes --yes-button Si --no-button No
if [ $? -eq 0 ]; then
	do_movistar_sip_account

	# ToDo: Detectar el router por la IP... si es comtrend lanzar esto
	whiptail --title "Comtrend VG-8050" --yesno "¿Desea configurar el Comtrend VG-8050 para utilizar los teléfonos analógicos?" 20 60 2 --yes-button Si --no-button No
	if [ $? -eq 0 ]; then
		do_comtrend_vg8050_fxs
	fi
fi